name: Release indexer
concurrency: release

on:
  push:
    branches:
      - master

jobs:
  release-moonriver:
    secrets:
      SQUID_API_KEY: ${{ secrets.SQUID_API_KEY }}
    needs:
      - release-moonbase
    uses: rmrk-team/skybreach-chunky-gifts/.github/workflows/release-env.yaml@master
    with:
      network: moonriver
      squid-name: skybreach-chunky-gifts
      squid-version: v0
