name: Release indexer by env

on:
  workflow_call:
    inputs:
      network:
        required: true
        type: string
      squid-name:
        required: true
        type: string
      squid-version:
        required: true
        type: string
    secrets:
      SQUID_API_KEY:
        description: 'A token passed from the caller workflow'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules
      - name: Install package.json dependencies with Yarn
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Login to sqd
        run: npx sqd auth --key ${{secrets.SQUID_API_KEY}}
      - name: release
        run: ./scripts/release.sh
        env:
          NETWORK: ${{inputs.network}}
          SQUID_VERSION: ${{inputs.squid-version}}
          SQUID_NAME: ${{inputs.squid-name}}
